use super::*;
use std::process::Stdio;
use tokio::io::AsyncWriteExt;

mod agent_skills;
mod ai_provider;
mod analytics;
mod asset_upload;
mod backup;
mod business_queries;
mod category_attributes;
mod category_catalog;
mod delivery_helpers;
mod evidence_export;
mod job_status;
#[cfg(test)]
mod pricing_strategy_tests;
mod product_status;
mod publish_loaders;
mod publish_payload;
mod settings;
mod shipment_helpers;
mod supplier_agent;
mod sync_persistence;
mod validation;
mod wechat_auth;

pub(in crate::commands) use agent_skills::*;
pub(in crate::commands) use ai_provider::*;
pub(in crate::commands) use analytics::*;
pub(in crate::commands) use asset_upload::*;
pub(in crate::commands) use backup::*;
pub(in crate::commands) use business_queries::*;
pub(in crate::commands) use category_attributes::*;
pub(in crate::commands) use category_catalog::*;
pub(in crate::commands) use delivery_helpers::*;
pub(in crate::commands) use evidence_export::*;
pub(in crate::commands) use job_status::*;
pub(in crate::commands) use product_status::*;
pub(in crate::commands) use publish_loaders::*;
pub(in crate::commands) use publish_payload::*;
pub(in crate::commands) use settings::*;
pub(in crate::commands) use shipment_helpers::*;
pub(in crate::commands) use supplier_agent::*;
pub(in crate::commands) use sync_persistence::*;
pub(in crate::commands) use validation::*;
pub(in crate::commands) use wechat_auth::*;
