import type {
  AftersaleEvidenceView,
  AftersaleRejectReasonView,
  AftersaleView,
  BackupInfo,
  CategoryCacheView,
  CategoryCatalogShopSummary,
  CategoryRelationView,
  CollectionTaskView,
  ExternalApiLogView,
  FreightTemplateView,
  GuaranteeOrderView,
  NotificationView,
  PurchaseTaskView,
  ShipmentView,
  ShopGroup,
  ShopListItem,
  SupplierAftersaleFollowupView,
  TaskRunView,
} from "../../types/app";
export const createPreviewGroups = (): ShopGroup[] => [
  {
    id: "group-default",
    name: "默认店铺组",
    status: "active",
    shop_count: 1,
    created_at: "2026-05-22T00:00:00+08:00",
  },
];
export const createPreviewShops = (): ShopListItem[] => [
  {
    id: "shop-preview",
    name: "预览店铺",
    appid: "wx-preview",
    status: "not_verified",
    group_id: "group-default",
    group_name: "默认店铺组",
    has_secret: false,
    token_expires_at: null,
    wechat_nickname: null,
    wechat_status: null,
    last_health_check_at: null,
    last_quota_remain: null,
    created_at: "2026-05-22T00:00:00+08:00",
  },
];
export const createPreviewTaskRuns = (): TaskRunView[] => [];
export const createPreviewCollectionTasks = (): CollectionTaskView[] => [
  {
    id: "col-preview-10001",
    title: "夏季薄款防晒衣女",
    source_url: "https://item.taobao.com/item.htm?id=10001",
    category_path: "服饰内衣 > 女装 > 防晒衣",
    target_shop_ids: [],
    status: "success",
    error_summary: null,
    collected_data: JSON.stringify({
      external_product_id: "tb-10001",
      title: "夏季薄款防晒衣女",
      source_url: "https://item.taobao.com/item.htm?id=10001",
      images: [
        "https://example.com/head-1.jpg",
        "https://example.com/head-2.jpg",
        "https://example.com/head-3.jpg",
      ],
      detail_images: ["https://example.com/detail-1.jpg"],
      skus: [
        {
          external_sku_id: "sku-1",
          specs: { 颜色: "米白色" },
          cost_price: 39,
          stock: 120,
        },
      ],
      supplier_name: "淘宝采集",
      supplier_product_id: "10001",
      category_hint: "服饰内衣 > 女装 > 防晒衣",
      brand_hint: "无品牌",
      weight_gram: 300,
      metadata: {},
    }),
    review_status: "passed",
    review_summary: "预览数据已通过审查",
    reviewed_data: null,
    review_result_json: null,
    reviewed_at: "2026-05-22T00:01:00+08:00",
    published_shop_ids: [],
    publish_job_ids: [],
    published_at: null,
    created_at: "2026-05-22T00:00:00+08:00",
    updated_at: "2026-05-22T00:01:00+08:00",
  },
];
export const createPreviewShipments = (): ShipmentView[] => [
  {
    id: "shipment-preview-failed",
    order_id: "order-preview-failed",
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    wechat_order_id: "420000000099",
    delivery_id: "SF",
    delivery_name: "顺丰",
    waybill_id: "SF0000000001",
    deliver_type: 1,
    status: "send_failed",
    error_code: "DELIVERY_PAYLOAD_INVALID",
    error_summary: "订单项缺少微信 product_id 或 sku_id，无法提交发货",
    submitted_at: null,
    created_at: "2026-05-22T00:09:00+08:00",
    updated_at: "2026-05-22T00:09:20+08:00",
  },
];
export const createPreviewPurchaseTasks = (): PurchaseTaskView[] => [
  {
    id: "purchase-preview-1",
    order_id: "order-preview-1",
    wechat_order_id: "420000000001",
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    status: "pending_purchase",
    external_product_id: "demo-1688-10001",
    external_sku_id: "black-m",
    source_url: "https://detail.1688.com/offer/10001.html",
    title: "夏季薄款防晒衣女",
    quantity: 1,
    sale_price: 2990,
    real_price: 2990,
    estimated_revenue: 2990,
    estimated_cost: null,
    estimated_profit: null,
    supplier_name: "1688 示例供货商",
    supplier_product_id: "ali-demo-10001",
    supplier_delivery_id: null,
    supplier_delivery_name: null,
    supplier_waybill_id: null,
    supplier_deliver_type: null,
    supplier_shipped_at: null,
    error_summary: null,
    created_at: "2026-05-22T00:08:00+08:00",
    updated_at: "2026-05-22T00:08:00+08:00",
  },
  {
    id: "purchase-preview-2",
    order_id: "order-preview-2",
    wechat_order_id: "420000000002",
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    status: "needs_mapping",
    external_product_id: null,
    external_sku_id: null,
    source_url: null,
    title: "待映射商品",
    quantity: 1,
    sale_price: 1990,
    real_price: 1990,
    estimated_revenue: 1990,
    estimated_cost: null,
    estimated_profit: null,
    supplier_name: null,
    supplier_product_id: null,
    supplier_delivery_id: null,
    supplier_delivery_name: null,
    supplier_waybill_id: null,
    supplier_deliver_type: null,
    supplier_shipped_at: null,
    error_summary: "缺少外部商品映射",
    created_at: "2026-05-22T00:08:00+08:00",
    updated_at: "2026-05-22T00:08:00+08:00",
  },
];
export const createPreviewAftersales = (): AftersaleView[] => [
  {
    id: "aftersale-preview-1",
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    order_id: "order-preview-1",
    wechat_order_id: "420000000001",
    wechat_aftersale_id: "after-sale-420000000001",
    status: "MERCHANT_PROCESSING",
    aftersale_type: "refund",
    reason: "买家申请退款，等待商家处理",
    refund_amount_cents: 2990,
    responsibility_party: null,
    responsibility_note: null,
    supplier_compensation_cents: 0,
    handled_at: null,
    last_action: null,
    last_action_status: null,
    last_action_error: null,
    last_action_note: null,
    last_action_at: null,
    evidence_count: 0,
    synced_at: "2026-05-22T00:18:00+08:00",
    updated_at: "2026-05-22T00:18:00+08:00",
  },
  {
    id: "aftersale-preview-failed",
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    order_id: null,
    wechat_order_id: "420000000088",
    wechat_aftersale_id: "after-sale-failed",
    status: "sync_failed",
    aftersale_type: null,
    reason: "微信售后详情失败：订单不存在或权限不足",
    refund_amount_cents: null,
    responsibility_party: null,
    responsibility_note: null,
    supplier_compensation_cents: 0,
    handled_at: null,
    last_action: null,
    last_action_status: null,
    last_action_error: null,
    last_action_note: null,
    last_action_at: null,
    evidence_count: 0,
    synced_at: "2026-05-22T00:18:10+08:00",
    updated_at: "2026-05-22T00:18:10+08:00",
  },
];
export const createPreviewAftersaleRejectReasons =
  (): AftersaleRejectReasonView[] => [
    {
      shop_id: "shop-preview",
      reject_reason_type: 6,
      reject_reason_type_text: "买家误操作/已协商取消申请",
      reject_reason: "已与买家沟通确认，本次售后先取消处理。",
      reject_scene: 1,
      reject_scene_text: "拒绝仅退款",
      synced_at: "2026-05-22T00:24:00+08:00",
    },
    {
      shop_id: "shop-preview",
      reject_reason_type: 4,
      reject_reason_type_text: "包裹在买家发起售后时已完成发货/揽收",
      reject_reason:
        "商品已完成发货或揽收，建议买家收到货后按实际情况重新发起售后。",
      reject_scene: 1,
      reject_scene_text: "拒绝仅退款",
      synced_at: "2026-05-22T00:24:00+08:00",
    },
    {
      shop_id: "shop-preview",
      reject_reason_type: 1,
      reject_reason_type_text: "已在约定时间发货且物流运输正常",
      reject_reason: "本店已在约定时间内完成发货，目前物流正常转运。",
      reject_scene: 1,
      reject_scene_text: "拒绝仅退款",
      synced_at: "2026-05-22T00:24:00+08:00",
    },
  ];
export const createPreviewGuaranteeOrders = (): GuaranteeOrderView[] => [
  {
    id: "guarantee-preview-1",
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    order_id: "order-preview-1",
    wechat_order_id: "420000000001",
    guarantee_order_id: "2000001077270153",
    guarantee_type: 2,
    guarantee_type_text: "坏损包退",
    status: "STATUS_WAIT_MERCHANT_PROOF",
    status_text: "等待商家举证",
    apply_reason: "买家反馈商品破损，需要商家补充凭证",
    pay_amount_cents: 2990,
    merchant_refuse_reason: null,
    handling_status: "pending",
    handling_note: "等待供应商提供发货前质检截图",
    responsibility_party: "unknown",
    supplier_compensation_cents: 0,
    handled_at: null,
    created_time: 1779428400,
    updated_time_unix: 1779429000,
    expire_time: 1779514800,
    complete_time: null,
    evidence_count: 1,
    synced_at: "2026-05-22T00:25:00+08:00",
    updated_at: "2026-05-22T00:25:00+08:00",
  },
  {
    id: "guarantee-preview-closed",
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    order_id: null,
    wechat_order_id: "420000000099",
    guarantee_order_id: "2000001077270999",
    guarantee_type: 1,
    guarantee_type_text: "假一赔三/四",
    status: "STATUS_USER_CANCEL",
    status_text: "用户取消申请",
    apply_reason: "用户取消纠纷申请",
    pay_amount_cents: 0,
    merchant_refuse_reason: null,
    handling_status: "ignored",
    handling_note: "买家已取消，无需继续处理",
    responsibility_party: "customer",
    supplier_compensation_cents: 0,
    handled_at: "2026-05-22T00:30:00+08:00",
    created_time: 1779342000,
    updated_time_unix: 1779345600,
    expire_time: null,
    complete_time: 1779345600,
    evidence_count: 0,
    synced_at: "2026-05-22T00:25:00+08:00",
    updated_at: "2026-05-22T00:25:00+08:00",
  },
];
export const createPreviewAftersaleEvidence = (): AftersaleEvidenceView[] => [
  {
    id: "evidence-preview-1",
    target_type: "guarantee",
    target_id: "guarantee-preview-1",
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    external_target_id: "2000001077270153",
    evidence_type: "supplier_proof",
    evidence_type_text: "供应商凭证",
    title: "供应商发货前质检截图",
    content_text:
      "已向供应商索要包装破损前后的质检截图，待人工核对后再决定是否提交平台。",
    local_file_path: "/Users/wangjunhao/Pictures/wx-xd-demo-proof.jpg",
    source_url: null,
    status: "draft",
    status_text: "草稿",
    created_at: "2026-05-22T00:34:00+08:00",
    updated_at: "2026-05-22T00:34:00+08:00",
  },
];
export const createPreviewSupplierAftersaleFollowups =
  (): SupplierAftersaleFollowupView[] => [
    {
      id: "supplier-followup-preview-1",
      target_type: "guarantee",
      target_id: "guarantee-preview-1",
      shop_id: "shop-preview",
      shop_name: "预览店铺",
      external_target_id: "2000001077270153",
      purchase_task_id: "purchase-preview-1",
      supplier_name: "示例供应商",
      followup_type: "evidence_request",
      followup_type_text: "索要凭证",
      status: "waiting_supplier",
      status_text: "等供应商",
      note: "已向供应商索要破损前质检截图和打包视频，只记录脱敏沟通摘要。",
      created_at: "2026-05-22T00:35:00+08:00",
      updated_at: "2026-05-22T00:35:00+08:00",
    },
  ];
export const createPreviewProfitAdjustments = (): Array<{
  order_id: string;
  kind: string;
  amount_cents: number;
}> => [
  { order_id: "order-preview-1", kind: "purchase_freight", amount_cents: 600 },
];
export const createPreviewDatabaseBackups = (): BackupInfo[] => [];
export const createPreviewExternalApiLogs = (): ExternalApiLogView[] => [
  {
    id: "external-api-log-preview",
    method: "POST",
    path: "/api/publish-jobs",
    status: "success",
    status_code: 200,
    error_code: null,
    request_summary:
      "request_id=req-preview products=1 target_groups=1 target_shops=0",
    response_summary: "ok",
    duration_ms: 38,
    created_at: "2026-05-22T00:17:00+08:00",
  },
];
export const createPreviewNotifications = (): NotificationView[] => [
  {
    id: "notification-preview-publish",
    severity: "critical",
    source_type: "publish_item",
    source_id: "item-preview",
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    title: "铺货任务失败",
    body: "店铺 预览店铺 铺货外部商品 demo-1688-10001 失败：缺少商品必填属性：材质（CATEGORY_ATTRS_NEED_AI_FILL）",
    status: "unread",
    data_json: '{"external_product_id":"demo-1688-10001"}',
    read_at: null,
    created_at: "2026-05-22T00:24:00+08:00",
    updated_at: "2026-05-22T00:24:00+08:00",
  },
  {
    id: "notification-preview-mapping",
    severity: "warning",
    source_type: "purchase_mapping",
    source_id: "order-item-preview-2",
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    title: "采购任务缺少外部商品映射",
    body: "订单 order-preview-2 的订单项缺少外部商品 ID 或外部 SKU，需人工补齐映射后再继续采购。",
    status: "unread",
    data_json: '{"order_id":"order-preview-2"}',
    read_at: null,
    created_at: "2026-05-22T00:23:00+08:00",
    updated_at: "2026-05-22T00:23:00+08:00",
  },
  {
    id: "notification-preview-aftersale",
    severity: "warning",
    source_type: "aftersale",
    source_id: "after-sale-420000000001",
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    title: "微信售后待处理",
    body: "售后单 after-sale-420000000001 当前状态为 MERCHANT_PROCESSING，需人工判断是否同意、拒绝或补充凭证。",
    status: "read",
    data_json: '{"wechat_order_id":"420000000001"}',
    read_at: "2026-05-22T00:25:00+08:00",
    created_at: "2026-05-22T00:18:00+08:00",
    updated_at: "2026-05-22T00:25:00+08:00",
  },
];
export const createPreviewCategoryCatalogShops =
  (): CategoryCatalogShopSummary[] => [
    {
      shop_id: "shop-preview",
      shop_name: "预览店铺",
      category_count: 3,
      detail_count: 1,
      product_rule_count: 1,
      delivery_rule_count: 1,
      category_relation_count: 1,
      active_category_relation_count: 1,
      freight_template_count: 1,
      last_category_sync_at: "2026-05-22T00:20:00+08:00",
      last_relation_sync_at: "2026-05-22T00:20:00+08:00",
      last_rule_sync_at: "2026-05-22T00:21:00+08:00",
      last_freight_sync_at: "2026-05-22T00:20:00+08:00",
    },
  ];
export const createPreviewCategoryCache = (): CategoryCacheView[] => [
  {
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    cat_id: 1000102,
    parent_cat_id: 1000101,
    level: 3,
    name: "防晒衣",
    product_attr_count: 6,
    sale_attr_count: 2,
    product_qua_count: 0,
    has_detail: true,
    has_product_rule: true,
    has_delivery_rule: true,
    is_available_for_shop: true,
    synced_at: "2026-05-22T00:20:00+08:00",
    detail_synced_at: "2026-05-22T00:21:00+08:00",
  },
  {
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    cat_id: 1000101,
    parent_cat_id: 1000001,
    level: 2,
    name: "女装",
    product_attr_count: 0,
    sale_attr_count: 0,
    product_qua_count: 0,
    has_detail: false,
    has_product_rule: false,
    has_delivery_rule: false,
    is_available_for_shop: false,
    synced_at: "2026-05-22T00:20:00+08:00",
    detail_synced_at: null,
  },
  {
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    cat_id: 1000001,
    parent_cat_id: null,
    level: 1,
    name: "服饰内衣",
    product_attr_count: 0,
    sale_attr_count: 0,
    product_qua_count: 0,
    has_detail: false,
    has_product_rule: false,
    has_delivery_rule: false,
    is_available_for_shop: false,
    synced_at: "2026-05-22T00:20:00+08:00",
    detail_synced_at: null,
  },
];
export const createPreviewCategoryRelations = (): CategoryRelationView[] => [
  {
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    cat_id: 1000102,
    category_name: "防晒衣",
    status: 1,
    uneffective_reason: null,
    effective_time: 1771603200,
    uneffective_time: null,
    qua_id: 900001,
    synced_at: "2026-05-22T00:20:00+08:00",
  },
];
export const createPreviewFreightTemplates = (): FreightTemplateView[] => [
  {
    shop_id: "shop-preview",
    shop_name: "预览店铺",
    template_id: "template-preview-1001",
    synced_at: "2026-05-22T00:20:00+08:00",
  },
];
